#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, to run this script, type that shell name before the whole command
#       line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced userland shells are not POSIX compliant.
#
#   (2) If you have a newline character in your JAVA_HOME or JAVA_OPTS, it can
#       cause problems. Try to keep these environment variables as single line.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    cd "$APP_HOME"
    app_path=$(readlink "$app_path")
done

# This is normally unused
# shellcheck disable=SC2034
app_bin="${app_path##*/}"
APP_HOME="$(cd "${APP_HOME:-./}" > /dev/null && pwd -P)"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NonStop* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD=$JAVA_HOME/bin/java
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$(ulimit -H -n) ||
            warn "Could not query maximum file descriptor limit"
      ;;
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)              
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
      ;;
    esac
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
# We will use the variable JAVA_OPTS (which is exported to allow embedding in setenv scripts)

# Handle the -Xmx and -Xms arguments which should not be split by spaces
# This is a workaround for the fact that the shell doesn't handle quoted arguments well
# We will collect all the arguments in a temporary variable and then process them

# Check for Java options in the environment
if [ -n "$JAVA_OPTS" ] ; then
    JAVA_OPTS="$JAVA_OPTS"
fi

# Check for Java options in the gradle.properties file
if [ -f "$APP_HOME/gradle.properties" ] ; then
    eval "$(grep -E "^org\.gradle\.jvmargs=" "$APP_HOME/gradle.properties" | sed 's/^org\.gradle\.jvmargs=//')"
fi

# Set default JVM options
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# If the user has specified JVM options, use them instead of the defaults
if [ -z "$JAVA_OPTS" ] && [ -z "$GRADLE_OPTS" ]; then
    JAVA_OPTS="$DEFAULT_JVM_OPTS"
fi

# Determine the class path
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Add the gradle home directory to the classpath
CLASSPATH="$CLASSPATH:$APP_HOME/gradle"

# Execute the java command
# shellcheck disable=SC2086
$JAVACMD $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
